Repository AxonFramework/ReferenceGuide, pull requests merged in 2018-08, with the labels that each got.

#57 Added event forwarding mode docs.
  part-ii-domain-logic/command-model.md
Labels: Type: Feature

#68 Added doc for EventTrackerStatus.
  part-iii-infrastructure-components/event-processing.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#69 Doc about serializer configuration.
  book.json
  part-iv-advanced-tuning/advanced-customizations.md
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#71 Added doc about Replay API.
  part-iii-infrastructure-components/event-processing.md
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#74 [#20] Add a Metrics and Monitoring section
  SUMMARY.md
  part-iv-advanced-tuning/metrics-and-monitoring.md
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#75 Provided documentation for Kafka Producer and MessageSource.
  part-iii-infrastructure-components/event-processing.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#76 Down tune MongoDb as a good fit the EventStore
  part-iii-infrastructure-components/repository-and-event-store.md
Labels: Priority 4: Would, Status: In Progress, Type: Enhancement

#77 [#73] Describe Message Dispatch Interceptors for the Event Bus
  part-iii-infrastructure-components/command-dispatching.md
  part-iii-infrastructure-components/event-processing.md
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#78 [#72] Describe Message Handler Interceptors for Event Processors
  part-iii-infrastructure-components/command-dispatching.md
  part-iii-infrastructure-components/event-processing.md
  part-iii-infrastructure-components/query-processing.md
  part-iv-advanced-tuning/metrics-and-monitoring.md
Labels: Priority 2: Should, Status: In Progress, Type: Feature

#79 [#70] Describe configuring metrics through Spring Boot
  part-iv-advanced-tuning/metrics-and-monitoring.md
Labels: Priority 3: Could, Status: In Progress, Type: Feature

#88 [#50] Added details about custom tracking token position.
  part-iii-infrastructure-components/event-processing.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#87 [#32] @CommandHandlerInterceptor doc.
  part-iii-infrastructure-components/command-dispatching.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#84 [#29] Three types of queries
  part-iii-infrastructure-components/query-processing.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#89 [#38] Added documentation about spawning new aggregate.
  part-ii-domain-logic/command-model.md
Labels: Priority 1: Must, Status: In Progress, Type: Feature
